apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ftps
  name: ftps-service
spec: 
  ports: 
    -
      port: 21
  selector: 
    app: ftps
  type: LoadBalancer

---
        
 apiVersion: apps/v1
 kind: Deployment
 metadata: 
   labels: 
     app: ftps
   name: ftps-deployment
 spec: 
   replicas: 1
   selector: 
     matchLabels: 
       app: ftps
   template: 
     metadata: 
       labels: 
         app: ftps
     spec: 
       containers: 
         - 
           image: ftps_service
           name: ftps
           imagePullPolicy: Never