apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysql
  name: mysql-service
spec: 
  ports: 
    -
      port: 3306
  selector: 
    app: mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
        - 
          image: mysql_service
          name: mysql
          imagePullPolicy: Never