apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: wordpress
  name: wordpress-service
spec: 
  ports: 
    -
      port: 5050
  selector: 
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress
  name: wordpress-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
        - 
          image: wordpress_service
          name: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050