# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    configMap.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: molabhai <molabhai@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/16 11:20:38 by molabhai          #+#    #+#              #
#    Updated: 2020/10/17 18:48:02 by molabhai         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.99.124-192.168.99.124