# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: molabhai <molabhai@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/16 11:21:18 by molabhai          #+#    #+#              #
#    Updated: 2020/10/17 19:00:01 by molabhai         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ftps
  name: ftps-service
spec: 
  ports: 
       - port: 21
         name: ftps-port
       - port: 20
         name: port-ftps
       - port: 31110
         name: ftps-passv-port
       - port: 31111
         name: passv-ftps-port
  selector: 
    app: ftps
  type: LoadBalancer
  externalIPs:
   - 192.168.99.135

---
        
apiVersion: apps/v1
kind: Deployment
metadata: 
     labels: 
       app: ftps
     name: ftps-deployment
spec: 
     replicas: 1
     selector: 
       matchLabels: 
         app: ftps
     template: 
       metadata: 
         labels: 
           app: ftps
       spec: 
         containers: 
           - 
             image: ftps_service
             name: ftps
             imagePullPolicy: Never
             ports:
              - containerPort: 21
              - containerPort: 31110
              - containerPort: 31111
