apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: nginx
  name: nginx-service
spec: 
  ports: 
    - port: 80
      name: http
    - port: 443
      name: https
  selector: 
    app: nginx
  type: LoadBalancer
  externalIPs:
    - 192.168.99.135
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx
  name: nginx-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: nginx_service
          name: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
