# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: molabhai <molabhai@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/16 11:21:11 by molabhai          #+#    #+#              #
#    Updated: 2020/10/17 18:55:04 by molabhai         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: phpmyadmin
  name: phpmyadmin-service
spec: 
  ports: 
    -
      port: 5000
      name: phpmyadmin
  selector: 
    app: phpmyadmin
  type: LoadBalancer
  externalIPs:
   - 192.168.99.135 
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: phpmyadmin
  name: phpmyadmin-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: phpmyadmin
  template: 
    metadata: 
      labels: 
        app: phpmyadmin
    spec: 
      restartPolicy: Always
      containers: 
        - 
          image: phpmyadmin_service
          name: phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
